name: Docker Image CI

on:
  push:
    paths:
    - 'Dockerfile'
    - '.github/workflows/dockerimage.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          context: ${{ github.workspace }}
          tags: latest
          tag_with_sha: true
          build_args: DATE=$(date +"%Y-%m-%d"), VERSION=${{ github.sha }}
